### ISSUE TITLE
JUNE: FILTER Master Issue

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#248]
Core purpose: Connect our various data sources directly to the affordable housing buildings. It allows users to find subsets of buildings that match a complex set of criteria. Provides an answer to questions like “Show me all Section 8 buildings with less than 100 units and in a census tract with above average income.” Stretch goal is to provide some interesting data visualizations comparing filtered buildings to
either all buildings or non-selected buildings.

- [x] Create filterable data set using [this list of 12 data fields](https://github.com/codefordc/housing-insights/issues/236#issuecomment-299218525) 
- [x] Add an API endpoint for this filterable data set
- [ ] Create front-end UI components for 3 main filter selection types: https://github.com/codefordc/housing-insights/issues/267
    - Over/under slider for a continuous range (e.g. proj_units_tot)
    - Multi-select from list (e.g. ward)
    - date range (e.g. poa_start)
- [x] Create a filter method that uses current state (from above) and returns a list of filtered ids. #268
- [ ] Design layout of filter UI vs. browse UI w/ appropriate legends showing what data has been selected and simple snapshot summary area. ~Issue: https://github.com/codefordc/housing-insights/issues/252~ (edited:) current action items: https://github.com/codefordc/housing-insights/issues/289
- [x] Implement filtering method on live site #273 
- [x] Add a legend / title that clearly displays filter criteria. 
- [ ] (stretch) Add summary visualizations comparing selected buildings to other buildings

**Comment by Nunie123** [comment]
The attached files should be used as an example response from the filter api endpoint.  This is what the data will look like once the endpoint is operational.  

As a reminder, the nlihc_id is duplicated in this data set.


[filter_api_response.zip](https://github.com/codefordc/housing-insights/files/990984/filter_api_response.zip)

**Comment by NealHumphrey** [comment]
@Nunie123 couple quick clarifications from you so we can do integration work with this sample data set during the Saturday hackathon:

1) I'm assuming this is the same one that you posted to Slack?
2) Does this contain all records to filter on?
3) Do you also have the associated SQL query used to make this? Can you commit it to github? I've been putting WIP sql queries into the /python/housinginsights/analysis folder until we come up w/ a system to integrate them.
4) You asked how to run the API - did you make any progress on adding the endpoint? It would be great to get it into the live version before our Saturday hackathon so the JS folks are able to work on it. If you're able to make a PR with it before then great, if not send me the SQL query you used and I can throw it in there. 

Remind me are you coming on Sat?

**Comment by ostermanj** [comment]
I can work on getting the left and right sidebars to slide in and out.

**Comment by NealHumphrey** [comment]
The api endpoint for the filterable data is up: http://hiapidemo.us-east-1.elasticbeanstalk.com/api/filter/
