### ISSUE TITLE
V2 MASTER ISSUE: 

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#403]
### General
- [x] URL state encoding #387  (status: mostly done, sidebars and testing needed)
- [x] (Jamie) Download CSV functionality #389 (status: open PR for MVP ready)
- [x] Refactor calculated fields to draw from ZoneFacts when it is available

### Map View
- [x] Lots of UI changes already implemented in demo-v2 branch soon to be merged to dev!
- [x] Finish making the filtering work in the merged filter/layer UI that is part of demo-v2 branch #392  
- [x] Project preview mode #391 (status: MVP done, need to add in charts)
- [x] Make clearing filters more usable #393 
    - [x] Fix bug in #442 - ui doesn't respond properly in some conditions
- [x] Mapbox zoom when filtering #397 
- [x] UI improvements to the filters for continuous data sets (sliders), plus adding datepickers #395
- [x] (Paul) UI improvements to the filters for categories (dropdown) #396 

**second priority**
- [ ] Bar Chart improvements #390 
- [ ] Reduce duplicated geoJson #433
- [x] (Paul) Mapbox dot animations #394 

### Project View (formerly called building view)
- [ ] Initial improvements to existing content #398 
- [x] Design what the project view should contain! #399  (status: mockup creation in progress)
- [ ] Do all the stuff created in 399

## Back end
- [x] Add a ZoneFacts table #388
    - [ ] Finish unit tests #388 (status - open PR needs review)
    - [ ] Add more fields to zonefacts (e.g. #419, others TBD)
- [x] Calculated fields on project table #430
    - [x] MVP with REAC scores
    - [ ] Add rest of the fields #430 
- [x] Refactor API to access the housinginsights package  #400
- [x] API endpoint for filter #431 
- [x] API endpoint for project table #432
- [ ] Automatically collect new data #402 (status: email job done in open PR, needs review). 
- [x] Api endpoint for ZoneFacts sliced for chloropleth #434

## Data Sources
- [ ] Propose new fields for map view; create ticket for each field as needed #401 
    - [ ] Nearest metro #424 
    - [ ] Topa #420 
    - [ ] REAC #425 (status: calculated in project table, needs entry in dataChoices.js)
- [ ] Update data documentation for all tables currently in the database

## General website stuff
- [ ] Add "?" links to all data fields linking to the appropriate data documentation page. ZoneFacts table will provide this for any calculated fields. 
- [ ] Add a landing page
- [ ] Add 3 saved analyses (using the url encoding) and use these to introduce the types of things the tool can do to new users; put these on the landing page. 
- [ ] Add a the navbar from the whole site to the top of the tool
- [ ] Add Google Analytics
- [x] Move the server to Code for DC hosting
