### ISSUE TITLE
Calculated fields on Project table

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#430]
Add a step to the code that updates the database to add calculated fields to the `project` table. Any project-specific data field that is contained in another table and that is used in the 'filter' endpoint should be added to the table. This means that to create the 'filter' endpoint, the CSV file for export, etc., we only need to join the `project` table to the `zone_facts` table and we will have all the data we need. This means some data is duplicated. 

Note that some fields from the Preservation Catalog are already calculated in this way - we should re-calculate these fields in case our additional data has altered their value (e.g. if a project in the PresCat receives a subsidy from DHCD that was not in the PresCat, the 'proj_units_assist_max' field might change). 

Typically, column names should take the form `<description>_<tablename>_<field_in_source_table>`. 
    - <description> corresponds to how the one-to-many relationship was resolved, i.e. "most_recent"
    - <tablename> is the exact table name from the database
    - <field_in_source_table> is the exact field name from the table that the value was pulled from. 

Every column that corresponds to a record in another table should also include the `id` field for that record in that table. For example, the `most_recent_reac_score_num` field would contain the score itself (e.g. 94), and a second column would contain the `reac_score.id` contents, named something like `most_recent_reac_score_id`. Note this is autogenerated using a uuid4 during the ingestion process, and so will not persist from database copy to database copy. However, assuming that the `update_project_table` script runs every time anything in the database is changed, this should always be the current copy of the uuid, that can be used for looking up the full record from the source table that corresponds to that data in the project table. 

*Note: pull request recommended any time a new field is completed*
MVP:
- [ ] Function that runs after 
- [ ] Most recent REAC score (part of #425)
    - `most_recent_react_score_num`
    - `reac_score_id`:

New Fields:
- [ ] Distance to nearest metro station (part of #424)
- [ ] Number of bus routes within 0.5 miles (part of #424)
- [ ] Most recent TOPA notice date (if one exists)
- [ ] `dc_tax.appraised_value_current_total`
- [ ] Appraised value per unit (appraised_value_current_total divided by proj_units_tot - note, should be at end of process so both numerator and denominator can be updated if needed)

Update existing calculated fields:
- Add 'id' records for all the current calculated fields listed below
- [ ] proj_units_assist_max (replace current value by looking in subsidy table)
- [ ] proj_units_assist_min (replace current value by looking in subsidy table)
- [ ] proj_units_tot (TBD - we should decide how to update this, what is authoritative source? CAMA? MAR? DHCD's database for those that are in it?)
- [ ] subsidy_end_first
- [ ] subsidy_end_last
- [ ] subsidy_start_first
- [ ] subsidy_start_last

**Comment by NealHumphrey** [comment]
This is completed for REAC - need to add additional fields. 

If you want to work on this ticket, post here re: which data fields you are claiming. I'll keep picking them off when I have time unless I see anyone else claim them.
