### ISSUE TITLE
September Master Issue

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#501]
This is still a work in progress - I need to create some issues for bullet points here, as well as go through all open issues to add any additional ones that need to be addressed before launch. 

Map View
- [ ] URL encoding finalizing (project in preview screen, 'summary' or 'matching' sidebar, fixing color coding on decode)
- [ ] (Jamie G.) Download CSV enhancements (#499)
- [ ] Search and filter by many addresses and TOPA (#500)
- [ ] Enhance project preview (list all subsidies, icons from project view)
- [ ] Change map view to only have 2 colors (match/nomatch)
- [ ] Clear 'Selected Project' if not part of a newly run filter

Project View
- [ ] Revamping project view #471 - need to turn this into multiple issues
- [ ] "Tabulate" as a D3 reusable chart
- [ ] Fix affordable housing nearby issues (#487)

Front end - If time
- [ ] Bar chart improvements (#390)
- [ ] Reduce duplicated geoJSON (#433)

Data Sources (needs both Python and JS)
- [ ] REAC #425 (status: calculated in project table, needs entry in dataChoices.js. Might also need to be added to api?)
- [ ] Nearest metro #424
- [ ] Topa #420

Data Processing 
- [ ] Add nlihc_id using multiple addresses 
    - [ ] TOPA table (refer to #404 for reference)
    - [ ] DC tax
    - [ ] Address
- [ ] Update data documentation for all tables currently in the database
- [ ] Add ANC's to weighting; add ANC to zone facts. 
- [ ] Set up a s3 bucket for uploading PresCat

## General Website Stuff
- [ ] Add "?" links to all data fields linking to the appropriate data documentation page. (#360)ZoneFacts table will provide this for any calculated fields. 
- [ ] Add a landing page
- [ ] Add 3 saved analyses (using the url encoding) and use these to introduce the types of things the tool can do to new users; put these on the landing page. 
- [ ] Add a the navbar from the whole site to the top of the tool
- [ ] Add Google Analytics
- [ ] Auto-population of data fields in Jekyll data documentation #105

**Comment by ostermanj** [comment]
@NealHumphrey I can jump on the finalizing URL encoding stuff. What's the issue with color-coding on decode?

**Comment by NealHumphrey** [comment]
@ostermanj When I load a saved URL (i.e. refresh the page with a few filters activated), the filters apply correctly to the right hand side panel summary stats - therefore it seems like the filterData is working properly - but all of the dots on the map are orange. If I then select an additional filiter on the page, dot-coloring resumes as normal. It seems to happen with all filters in my browser (Chrome on Windows) - I can come up with specific scenarios if you are not able to recreate. I'm online working today (starting with reviewing your open pull requests) so let me know if you can't replicate the problem.

**Comment by ostermanj** [comment]
Got the color coding work locally. Will push after finishing the other decode tasks. 

__
The filter decoding was happening too quickly after initialLayers were added, before they were fully rendered. Solutions uses mapBox's render event, checks against state of initialLayersAdded and !isFilterInitialized to setState initialProjectsRendered. router.initFilters subscribes to that stateChange and turns isFilterInitialized to true so that this stateChange fires only once
